"""Reusable Hypothesis strategies for the domain (CORE-45).

Built here, with the models, so W2 and W5 do not each write throwaway versions.

**These are hand-written, and they have to be.** `st.from_type()` cannot read a Pydantic
constraint: against an alias declared with `StringConstraints` it warns and yields the empty
string, and against one declared with `Field` it warns not at all and yields the empty string
anyway. Both were measured. `pyproject.toml` turns the first into a hard failure and
`tests/unit/test_identifiers.py` pins every alias to the form that triggers it — but the real
defence is that nothing here calls `from_type` in the first place.

Values are constructed directly rather than filtered, per core.md: `st.from_regex(PATTERN,
fullmatch=True)` against the same constant the alias uses produced 0 invalid examples in 400.
A filter-based approach would thrash on a 3-to-64-character pattern and shrink badly.

Notion §12A and `core.md` both name eight strategy groups. Four are built here. The other four —
`workflows`, `views`, `releases`, `artifacts` — have no models until W4, W5 and W7a, and
`DEFERRED_GROUPS` records that rather than leaving the gap for a reader to infer.
"""

from tests.strategies.authoring import reformatted
from tests.strategies.commands import (
    add_elements,
    change_sets,
    rename_elements,
    retire_elements,
)
from tests.strategies.domain import element_details, elements, references, status_dimensions
from tests.strategies.ids import STRATEGY_BY_ALIAS, digests, element_ids, model_ids
from tests.strategies.relations import (
    coherent_models,
    full_models,
    interactions,
    notation_bindings,
    reference_links,
    relationships,
)

__all__ = [
    "DEFERRED_GROUPS",
    "STRATEGY_BY_ALIAS",
    "add_elements",
    "change_sets",
    "coherent_models",
    "digests",
    "element_details",
    "element_ids",
    "elements",
    "full_models",
    "interactions",
    "model_ids",
    "notation_bindings",
    "reference_links",
    "references",
    "reformatted",
    "relationships",
    "rename_elements",
    "retire_elements",
    "status_dimensions",
]

DEFERRED_GROUPS: dict[str, str] = {
    "workflows": "W7b — BPMN profile; W1's behaviour detail is generated by `element_details`",
    "views": "W7a — no ViewDefinition exists (PROJ-02, PROJ-03)",
    "releases": "W4 — no release manifest exists (DATA-21..DATA-24)",
    "artifacts": "W7a — no projection or render artifact exists (PROJ-05, PROJ-06)",
}
"""The four groups core.md names that W1 cannot build, and what unblocks each."""
